import { Skin, LevelConfig, DailyChallenge } from '../types/game';

export const SKINS: Skin[] = [
  // --- COMMON (4 Skins) ---
  {
    id: 'amber',
    name: 'Amber',
    rarity: 'Common',
    color: '#3b82f6',
    secondaryColor: '#bfdbfe',
    glowColor: 'rgba(59, 130, 246, 0.7)',
    trailColor: 'rgba(96, 165, 250, 0.4)',
    description: 'Precision amber cyber tracker infused with high-frequency pheromones.',
    unlockedByDefault: true,
    cost: 0,
  },
  {
    id: 'golden_amber',
    name: 'Gold',
    rarity: 'Common',
    color: '#f59e0b',
    secondaryColor: '#fef3c7',
    glowColor: 'rgba(245, 158, 11, 0.7)',
    trailColor: 'rgba(251, 191, 36, 0.4)',
    description: 'Natural hardened amber resin with golden hexagonal bio-luminescence.',
    unlockedByDefault: false,
    cost: 150,
  },
  {
    id: 'crimson',
    name: 'Crimson',
    rarity: 'Common',
    color: '#ef4444',
    secondaryColor: '#fee2e2',
    glowColor: 'rgba(239, 68, 68, 0.7)',
    trailColor: 'rgba(248, 113, 113, 0.5)',
    description: 'Blazing soldier ant pheromone essence that burns with blood rage.',
    unlockedByDefault: false,
    cost: 200,
  },
  {
    id: 'forest_moss',
    name: 'Moss',
    rarity: 'Common',
    color: '#15803d',
    secondaryColor: '#dcfce7',
    glowColor: 'rgba(21, 128, 61, 0.7)',
    trailColor: 'rgba(34, 197, 94, 0.4)',
    description: 'Camouflaged forest bark with natural spore-cloud dispersion.',
    unlockedByDefault: false,
    cost: 280,
  },

  // --- RARE (5 Skins) ---
  {
    id: 'cyan',
    name: 'Cyan',
    rarity: 'Rare',
    color: '#06b6d4',
    secondaryColor: '#cffafe',
    glowColor: 'rgba(6, 182, 212, 0.75)',
    trailColor: 'rgba(34, 211, 238, 0.5)',
    description: 'Experimental cybernetic hive matrix tracking cursor.',
    unlockedByDefault: false,
    cost: 450,
  },
  {
    id: 'toxic',
    name: 'Toxic',
    rarity: 'Rare',
    color: '#10b981',
    secondaryColor: '#d1fae5',
    glowColor: 'rgba(168, 85, 247, 0.75)',
    trailColor: 'rgba(52, 211, 153, 0.5)',
    description: 'Corrosive formic acid vapor dripping with lethal bio-hazard energy.',
    unlockedByDefault: false,
    cost: 550,
  },
  {
    id: 'amethyst',
    name: 'Amethyst',
    rarity: 'Rare',
    color: '#a855f7',
    secondaryColor: '#f3e8ff',
    glowColor: 'rgba(168, 85, 247, 0.75)',
    trailColor: 'rgba(192, 132, 252, 0.5)',
    description: 'Supreme subterranean queen aura radiating mystical void energy.',
    unlockedByDefault: false,
    cost: 650,
  },
  {
    id: 'solar_flare',
    name: 'Solar',
    rarity: 'Rare',
    color: '#f97316',
    secondaryColor: '#ffedd5',
    glowColor: 'rgba(249, 115, 22, 0.75)',
    trailColor: 'rgba(251, 146, 60, 0.5)',
    description: 'Thermonuclear heat core that leaves trailing solar plasma ripples.',
    unlockedByDefault: false,
    cost: 750,
  },
  {
    id: 'glacial_cryo',
    name: 'Glacial',
    rarity: 'Rare',
    color: '#38bdf8',
    secondaryColor: '#e0f2fe',
    glowColor: 'rgba(56, 189, 248, 0.75)',
    trailColor: 'rgba(125, 211, 252, 0.5)',
    description: 'Sub-zero cryo frost crystals that chill surrounding dirt particles.',
    unlockedByDefault: false,
    cost: 900,
  },

  // --- EPIC (6 Skins) ---
  {
    id: 'emerald_matrix',
    name: 'Emerald',
    rarity: 'Epic',
    color: '#22c55e',
    secondaryColor: '#dcfce7',
    glowColor: 'rgba(34, 197, 94, 0.8)',
    trailColor: 'rgba(74, 222, 128, 0.5)',
    description: 'High-frequency digital code stream pulsing through synthetic insect veins.',
    unlockedByDefault: false,
    cost: 1100,
  },
  {
    id: 'obsidian_shadow',
    name: 'Obsidian',
    rarity: 'Epic',
    color: '#94a3b8',
    secondaryColor: '#f1f5f9',
    glowColor: 'rgba(148, 163, 184, 0.8)',
    trailColor: 'rgba(203, 213, 225, 0.4)',
    description: 'Stealth volcanic glass forged in subterranean fissures to absorb light.',
    unlockedByDefault: false,
    cost: 1250,
  },
  {
    id: 'synthwave_pink',
    name: 'Synthwave',
    rarity: 'Epic',
    color: '#ec4899',
    secondaryColor: '#fce7f3',
    glowColor: 'rgba(236, 72, 153, 0.8)',
    trailColor: 'rgba(244, 114, 182, 0.5)',
    description: 'Retro-futuristic neon highway grid radiating high-energy synth pulses.',
    unlockedByDefault: false,
    cost: 1400,
  },
  {
    id: 'electric_volt',
    name: 'Volt',
    rarity: 'Epic',
    color: '#eab308',
    secondaryColor: '#fef9c3',
    glowColor: 'rgba(234, 179, 8, 0.85)',
    trailColor: 'rgba(250, 204, 21, 0.6)',
    description: 'Arcing electrostatic discharges dancing across hyper-sensitive antennae.',
    unlockedByDefault: false,
    cost: 1600,
  },
  {
    id: 'radioactive_waste',
    name: 'Hazard',
    rarity: 'Epic',
    color: '#84cc16',
    secondaryColor: '#ecfccb',
    glowColor: 'rgba(132, 204, 22, 0.85)',
    trailColor: 'rgba(163, 230, 53, 0.6)',
    description: 'Unstable isotope radiation dripping with glowing bio-mutagen essence.',
    unlockedByDefault: false,
    cost: 1800,
  },
  {
    id: 'magma_core',
    name: 'Magma',
    rarity: 'Epic',
    color: '#dc2626',
    secondaryColor: '#fee2e2',
    glowColor: 'rgba(220, 38, 38, 0.85)',
    trailColor: 'rgba(239, 68, 68, 0.6)',
    description: 'Molten magma shell flowing with liquid basalt and micro-eruptions.',
    unlockedByDefault: false,
    cost: 2000,
  },

  // --- LEGENDARY (5 Skins) ---
  {
    id: 'chrono_brass',
    name: 'Chrono',
    rarity: 'Legendary',
    color: '#d97706',
    secondaryColor: '#fef3c7',
    glowColor: 'rgba(217, 119, 6, 0.85)',
    trailColor: 'rgba(245, 158, 11, 0.55)',
    description: 'Intricate brass clockwork gears ticking in synchrony with level BPM.',
    unlockedByDefault: false,
    cost: 2500,
  },
  {
    id: 'ghost_phantom',
    name: 'Ghost',
    rarity: 'Legendary',
    color: '#e2e8f0',
    secondaryColor: '#ffffff',
    glowColor: 'rgba(226, 232, 240, 0.85)',
    trailColor: 'rgba(248, 250, 252, 0.6)',
    description: 'Ethereal spectral projection phasing through physical terrarium boundaries.',
    unlockedByDefault: false,
    cost: 2800,
  },
  {
    id: 'blood_moon',
    name: 'Blood',
    rarity: 'Legendary',
    color: '#b91c1c',
    secondaryColor: '#fecaca',
    glowColor: 'rgba(185, 28, 28, 0.85)',
    trailColor: 'rgba(220, 38, 38, 0.6)',
    description: 'Occult crimson moon aura invoking the ferocity of ancient ant broods.',
    unlockedByDefault: false,
    cost: 3200,
  },
  {
    id: 'deep_nebula',
    name: 'Nebula',
    rarity: 'Legendary',
    color: '#6366f1',
    secondaryColor: '#e0e7ff',
    glowColor: 'rgba(99, 102, 241, 0.85)',
    trailColor: 'rgba(129, 140, 248, 0.6)',
    description: 'Swirling stellar dust and birthplaces of cosmic ant dynasties.',
    unlockedByDefault: false,
    cost: 3600,
  },
  {
    id: 'quantum_pulsar',
    name: 'Pulsar',
    rarity: 'Legendary',
    color: '#8b5cf6',
    secondaryColor: '#ede9fe',
    glowColor: 'rgba(139, 92, 246, 0.9)',
    trailColor: 'rgba(167, 139, 250, 0.6)',
    description: 'High-energy gamma beam emitter spinning at blinding rotational velocity.',
    unlockedByDefault: false,
    cost: 4000,
  },

  // --- MYTHIC (4 Skins) ---
  {
    id: 'aurora_spirit',
    name: 'Aurora',
    rarity: 'Mythic',
    color: '#2dd4bf',
    secondaryColor: '#ccfbf1',
    glowColor: 'rgba(45, 212, 191, 0.9)',
    trailColor: 'rgba(94, 234, 212, 0.65)',
    description: 'Celestial geomagnetic curtain waving with luminous teal and emerald radiance.',
    unlockedByDefault: false,
    cost: 5000,
  },
  {
    id: 'carbon_titanium',
    name: 'Titanium',
    rarity: 'Mythic',
    color: '#64748b',
    secondaryColor: '#e2e8f0',
    glowColor: 'rgba(100, 116, 139, 0.9)',
    trailColor: 'rgba(148, 163, 184, 0.65)',
    description: 'Aerospace-grade composite weave reinforced with nano-diamond coatings.',
    unlockedByDefault: false,
    cost: 6000,
  },
  {
    id: 'queen_regalia',
    name: 'Queen',
    rarity: 'Mythic',
    color: '#f43f5e',
    secondaryColor: '#ffe4e6',
    glowColor: 'rgba(244, 63, 94, 0.95)',
    trailColor: 'rgba(251, 113, 133, 0.7)',
    description: 'The ceremonial crown of the colony sovereign, carved from crystalline chitin.',
    unlockedByDefault: false,
    cost: 7500,
  },
  {
    id: 'celestial_sovereign',
    name: 'Celestial',
    rarity: 'Mythic',
    color: '#fbbf24',
    secondaryColor: '#fffbeb',
    glowColor: 'rgba(251, 191, 36, 0.95)',
    trailColor: 'rgba(253, 224, 71, 0.7)',
    description: 'Apex divine transcendence. Golden starlight wings granting supreme colony mastery.',
    unlockedByDefault: false,
    cost: 9000,
  },
  {
    id: 'dark_singularity',
    name: 'Singularity',
    rarity: 'Mythic',
    color: '#818cf8',
    secondaryColor: '#e0e7ff',
    glowColor: 'rgba(129, 140, 248, 0.95)',
    trailColor: 'rgba(99, 102, 241, 0.75)',
    description: 'Gravitational event horizon collapsing light into an impenetrable void vortex.',
    unlockedByDefault: false,
    cost: 10000,
  },
  {
    id: 'hyper_drive',
    name: 'Hyperdrive',
    rarity: 'Mythic',
    color: '#06b6d4',
    secondaryColor: '#cffafe',
    glowColor: 'rgba(6, 182, 212, 0.95)',
    trailColor: 'rgba(34, 211, 238, 0.75)',
    description: 'Faster-than-light tachyon drive projecting relativistic quantum trails.',
    unlockedByDefault: false,
    cost: 12000,
  },
  {
    id: 'prism_rainbow',
    name: 'Prism',
    rarity: 'Legendary',
    color: '#ec4899',
    secondaryColor: '#fdf2f8',
    glowColor: 'rgba(236, 72, 153, 0.9)',
    trailColor: 'rgba(244, 114, 182, 0.65)',
    description: 'Refractive diamond facet splitting pure white photons into a rainbow spectrum.',
    unlockedByDefault: false,
    cost: 4500,
  },
  {
    id: 'bio_nanite',
    name: 'Nanite',
    rarity: 'Epic',
    color: '#67e8f9',
    secondaryColor: '#ecfeff',
    glowColor: 'rgba(103, 232, 249, 0.85)',
    trailColor: 'rgba(165, 243, 252, 0.6)',
    description: 'Self-replicating microscopic cyber-nanites assembling instant force-fields.',
    unlockedByDefault: false,
    cost: 2200,
  },
];

export const DAILY_CHALLENGES: DailyChallenge[] = [
  {
    id: 'daily_dodge',
    title: 'Swarm Evasion',
    description: 'Dodge 100 ants in close proximity across any level runs.',
    type: 'dodge_ants',
    targetCount: 100,
    rewardPts: 1000,
    rewardSugar: 50,
    iconName: 'ShieldAlert',
  },
  {
    id: 'daily_sugar',
    title: 'Sweet Sugar Harvest',
    description: 'Collect 20 glowing sugar cubes during gameplay.',
    type: 'collect_sugar',
    targetCount: 20,
    rewardPts: 1000,
    rewardSugar: 60,
    iconName: 'Cookie',
  },
  {
    id: 'daily_portals',
    title: 'Tempo Warp Navigator',
    description: 'Enter 8 speed portals (0.5x, 1.5x, 2.0x) to manipulate level tempo.',
    type: 'speed_portals',
    targetCount: 8,
    rewardPts: 1250,
    rewardSugar: 75,
    iconName: 'Zap',
  },
  {
    id: 'daily_hard_clear',
    title: 'Apex Colony Breach',
    description: 'Survive and complete any chamber of Hard, Harder, Insane, or Crazy difficulty.',
    type: 'beat_hard',
    targetCount: 1,
    rewardPts: 1500,
    rewardSugar: 100,
    iconName: 'Trophy',
  },
  {
    id: 'daily_freemode',
    title: 'Endless Free Mode Endurance',
    description: 'Survive 35+ seconds in Endless Free Mode as difficulties randomize every 15s.',
    type: 'survive_free_mode',
    targetCount: 35,
    rewardPts: 2000,
    rewardSugar: 150,
    iconName: 'Flame',
  },
  {
    id: 'daily_score_blitz',
    title: 'Score Blitz Master',
    description: 'Achieve at least 5,000 PTS in a single level run.',
    type: 'score_milestone',
    targetCount: 5000,
    rewardPts: 2500,
    rewardSugar: 200,
    iconName: 'Award',
  },
];

export const DIFFICULTY_COLORS: Record<string, string> = {
  Easy: '#38bdf8',
  Normal: '#3b82f6',
  Hard: '#2563eb',
  Harder: '#818cf8',
  Insane: '#c084fc',
  Crazy: '#f43f5e',
};

export const LEVELS: LevelConfig[] = [
  // --- EASY (4 Levels) ---
  {
    id: 1,
    name: 'happiness',
    difficulty: 'Easy',
    difficultyColor: '#38bdf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1622289',
    songTitle: 'Happiness',
    artist: 'Newgrounds #1622289',
    bpm: 115,
    durationSeconds: 30,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 1,
    maxAnts: 14,
    mechanicId: 'tutorial',
    mechanicName: 'tutorial',
    mechanicHint: 'run away from the ants with ur cursor • destroy anthills to get points • use power ups!',
  },
  {
    id: 2,
    name: 'Sunny Meadow',
    difficulty: 'Easy',
    difficultyColor: '#38bdf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1622290',
    songTitle: 'Sunny Meadow',
    artist: 'Newgrounds #1622290',
    bpm: 122,
    durationSeconds: 65,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 2,
    maxAnts: 40,
    mechanicId: 'honey_traps',
    mechanicName: 'honey traps',
    mechanicHint: 'click honey jars to spill honey and freeze surrounding ants',
  },
  {
    id: 3,
    name: 'Ant Trail',
    difficulty: 'Easy',
    difficultyColor: '#38bdf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1621000',
    songTitle: 'Ant Trail',
    artist: 'Newgrounds #1621000',
    bpm: 126,
    durationSeconds: 70,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 2,
    maxAnts: 42,
    mechanicId: 'emp_pods',
    mechanicName: 'emp pods',
    mechanicHint: 'click glowing emp orbs to freeze the entire colony for 3s',
  },
  {
    id: 4,
    name: 'Pebble Path',
    difficulty: 'Easy',
    difficultyColor: '#38bdf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1619500',
    songTitle: 'Pebble Path',
    artist: 'Newgrounds #1619500',
    bpm: 128,
    durationSeconds: 70,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 3,
    maxAnts: 45,
    mechanicId: 'warp_gates',
    mechanicName: 'speed warps',
    mechanicHint: 'pass speed portals to blast pursuing ants with shockwaves',
  },

  // --- NORMAL (4 Levels) ---
  {
    id: 5,
    name: "Dawn'n'Drive",
    difficulty: 'Normal',
    difficultyColor: '#3b82f6',
    songUrl: 'https://www.newgrounds.com/audio/listen/1616642',
    songTitle: "Dawn'n'Drive",
    artist: 'Newgrounds #1616642',
    bpm: 138,
    durationSeconds: 75,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 3,
    maxAnts: 55,
    mechanicId: 'honey_traps',
    mechanicName: 'honey traps',
    mechanicHint: 'click honey nodes to glue and slow down surrounding ants',
  },
  {
    id: 6,
    name: 'Midnight Run',
    difficulty: 'Normal',
    difficultyColor: '#3b82f6',
    songUrl: 'https://www.newgrounds.com/audio/listen/1615500',
    songTitle: 'Midnight Run',
    artist: 'Newgrounds #1615500',
    bpm: 136,
    durationSeconds: 75,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 3,
    maxAnts: 58,
    mechanicId: 'sonic_pulse',
    mechanicName: 'sonic pulse',
    mechanicHint: 'click anywhere to emit sonic shockwaves repelling nearby ants',
  },
  {
    id: 7,
    name: 'Tunnel Rush',
    difficulty: 'Normal',
    difficultyColor: '#3b82f6',
    songUrl: 'https://www.newgrounds.com/audio/listen/1615200',
    songTitle: 'Tunnel Rush',
    artist: 'Newgrounds #1615200',
    bpm: 140,
    durationSeconds: 80,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 3,
    maxAnts: 62,
    mechanicId: 'laser_breaker',
    mechanicName: 'laser nodes',
    mechanicHint: 'click laser emitters to disable them for 6 seconds',
  },
  {
    id: 8,
    name: 'Dust & Grit',
    difficulty: 'Normal',
    difficultyColor: '#3b82f6',
    songUrl: 'https://www.newgrounds.com/audio/listen/1615000',
    songTitle: 'Dust & Grit',
    artist: 'Newgrounds #1615000',
    bpm: 142,
    durationSeconds: 80,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 4,
    maxAnts: 65,
    mechanicId: 'pheromone_bait',
    mechanicName: 'pheromone bait',
    mechanicHint: 'click to deploy sugar bait that lures all ants away',
  },

  // --- HARD (4 Levels) ---
  {
    id: 9,
    name: 'Experience',
    difficulty: 'Hard',
    difficultyColor: '#2563eb',
    songUrl: 'https://www.newgrounds.com/audio/listen/1614871',
    songTitle: 'Experience',
    artist: 'Newgrounds #1614871',
    bpm: 150,
    durationSeconds: 85,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 4,
    maxAnts: 75,
    mechanicId: 'fire_extinguisher',
    mechanicName: 'fire extinguish',
    mechanicHint: 'click blazing fire ant nests to douse flames & clear embers',
  },
  {
    id: 10,
    name: 'Quartz Cavern',
    difficulty: 'Hard',
    difficultyColor: '#2563eb',
    songUrl: 'https://www.newgrounds.com/audio/listen/1613500',
    songTitle: 'Quartz Cavern',
    artist: 'Newgrounds #1613500',
    bpm: 152,
    durationSeconds: 85,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 4,
    maxAnts: 80,
    mechanicId: 'orbital_blast',
    mechanicName: 'orbital strikes',
    mechanicHint: 'click targeting reticles to call orbital blast strikes',
  },
  {
    id: 11,
    name: 'Subterranean',
    difficulty: 'Hard',
    difficultyColor: '#2563eb',
    songUrl: 'https://www.newgrounds.com/audio/listen/1612000',
    songTitle: 'Subterranean',
    artist: 'Newgrounds #1612000',
    bpm: 154,
    durationSeconds: 90,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 4,
    maxAnts: 85,
    mechanicId: 'gravity_core',
    mechanicName: 'gravity well',
    mechanicHint: 'click gravity core to pull & crush nearby swarm in an implosion',
  },
  {
    id: 12,
    name: 'Iron Mandible',
    difficulty: 'Hard',
    difficultyColor: '#2563eb',
    songUrl: 'https://www.newgrounds.com/audio/listen/1610000',
    songTitle: 'Iron Mandible',
    artist: 'Newgrounds #1610000',
    bpm: 155,
    durationSeconds: 90,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 5,
    maxAnts: 90,
    mechanicId: 'shield_battery',
    mechanicName: 'shield battery',
    mechanicHint: 'click glowing power cells to trigger an invulnerable shield burst',
  },

  // --- HARDER (4 Levels) ---
  {
    id: 13,
    name: 'Dying to Live',
    difficulty: 'Harder',
    difficultyColor: '#818cf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1607400',
    songTitle: 'Dying to Live',
    artist: 'Newgrounds #1607400',
    bpm: 162,
    durationSeconds: 95,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 5,
    maxAnts: 100,
    mechanicId: 'queen_cocoons',
    mechanicName: 'queen cocoons',
    mechanicHint: 'spam-click brood cocoons before they hatch into titans',
  },
  {
    id: 14,
    name: 'Magma Chamber',
    difficulty: 'Harder',
    difficultyColor: '#818cf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1606200',
    songTitle: 'Magma Chamber',
    artist: 'Newgrounds #1606200',
    bpm: 164,
    durationSeconds: 95,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 5,
    maxAnts: 105,
    mechanicId: 'tesla_coils',
    mechanicName: 'tesla coils',
    mechanicHint: 'click electric pylons to chain lightning through the swarm',
  },
  {
    id: 15,
    name: 'Red Alert Colony',
    difficulty: 'Harder',
    difficultyColor: '#818cf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1605000',
    songTitle: 'Red Alert Colony',
    artist: 'Newgrounds #1605000',
    bpm: 166,
    durationSeconds: 100,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 5,
    maxAnts: 110,
    mechanicId: 'quake_fissure',
    mechanicName: 'seismic faults',
    mechanicHint: 'click seismic lines to trigger ant-clearing cave-ins',
  },
  {
    id: 16,
    name: 'Formic Storm',
    difficulty: 'Harder',
    difficultyColor: '#818cf8',
    songUrl: 'https://www.newgrounds.com/audio/listen/1604000',
    songTitle: 'Formic Storm',
    artist: 'Newgrounds #1604000',
    bpm: 168,
    durationSeconds: 100,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 6,
    maxAnts: 115,
    mechanicId: 'acid_geysers',
    mechanicName: 'acid geysers',
    mechanicHint: 'click bubbling vents to purge corrosive acid outward',
  },

  // --- INSANE (4 Levels) ---
  {
    id: 17,
    name: 'Vision',
    difficulty: 'Insane',
    difficultyColor: '#c084fc',
    songUrl: 'https://www.newgrounds.com/audio/listen/1418933',
    songTitle: 'Vision',
    artist: 'Newgrounds #1418933',
    bpm: 175,
    durationSeconds: 105,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 6,
    maxAnts: 125,
    mechanicId: 'sonic_subwoofer',
    mechanicName: 'bass subwoofers',
    mechanicHint: 'click pulsing bass nodes to emit sonic shockwaves',
  },
  {
    id: 18,
    name: 'Neuro Colony',
    difficulty: 'Insane',
    difficultyColor: '#c084fc',
    songUrl: 'https://www.newgrounds.com/audio/listen/1419500',
    songTitle: 'Neuro Colony',
    artist: 'Newgrounds #1419500',
    bpm: 178,
    durationSeconds: 105,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 6,
    maxAnts: 130,
    mechanicId: 'cryo_barrels',
    mechanicName: 'cryo barrels',
    mechanicHint: 'click liquid nitrogen barrels to freeze pursuers in ice',
  },
  {
    id: 19,
    name: 'Synapse Overload',
    difficulty: 'Insane',
    difficultyColor: '#c084fc',
    songUrl: 'https://www.newgrounds.com/audio/listen/1420100',
    songTitle: 'Synapse Overload',
    artist: 'Newgrounds #1420100',
    bpm: 180,
    durationSeconds: 110,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 6,
    maxAnts: 135,
    mechanicId: 'chrono_warp',
    mechanicName: 'chrono time warp',
    mechanicHint: 'click chrono spheres to slow time to matrix speed',
  },
  {
    id: 20,
    name: 'Hyperhive Genesis',
    difficulty: 'Insane',
    difficultyColor: '#c084fc',
    songUrl: 'https://www.newgrounds.com/audio/listen/1421000',
    songTitle: 'Hyperhive Genesis',
    artist: 'Newgrounds #1421000',
    bpm: 182,
    durationSeconds: 110,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 7,
    maxAnts: 140,
    mechanicId: 'plasma_artillery',
    mechanicName: 'plasma cannons',
    mechanicHint: 'spam-click artillery cannons to barrage the hive with plasma',
  },

  // --- CRAZY (3 Levels) ---
  {
    id: 21,
    name: 'Apocalypse Hive',
    difficulty: 'Crazy',
    difficultyColor: '#f43f5e',
    songUrl: 'https://www.newgrounds.com/audio/listen/1422000',
    songTitle: 'Apocalypse Hive',
    artist: 'Newgrounds #1422000',
    bpm: 190,
    durationSeconds: 115,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 7,
    maxAnts: 155,
    mechanicId: 'titan_slayer',
    mechanicName: 'titan slayer',
    mechanicHint: 'click colossal titan ants directly to stagger & damage them',
  },
  {
    id: 22,
    name: 'Quantum Swarm',
    difficulty: 'Crazy',
    difficultyColor: '#f43f5e',
    songUrl: 'https://www.newgrounds.com/audio/listen/1423000',
    songTitle: 'Quantum Swarm',
    artist: 'Newgrounds #1423000',
    bpm: 200,
    durationSeconds: 120,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 8,
    maxAnts: 170,
    mechanicId: 'core_meltdown',
    mechanicName: 'hive meltdown',
    mechanicHint: 'spam-click overheating reactor cores to blast the hive',
  },
  {
    id: 23,
    name: 'Omega Extinction',
    difficulty: 'Crazy',
    difficultyColor: '#f43f5e',
    songUrl: 'https://www.newgrounds.com/audio/listen/1424000',
    songTitle: 'Omega Extinction',
    artist: 'Newgrounds #1424000',
    bpm: 215,
    durationSeconds: 125,
    themeColor: '#ffffff',
    bgColor: '#000000',
    spawnerCount: 8,
    maxAnts: 185,
    mechanicId: 'queen_fortress',
    mechanicName: 'queen fortress',
    mechanicHint: 'spam-click central queen fortress while dodging elite broods',
  },
];

export const DIFFICULTY_ANT_SCALING: Record<
  string,
  { base: number; worker: number; fire: number; acid: number; titan?: number; label: string; tag: string }
> = {
  Easy: { base: 4.8, worker: 4.8, fire: 5.2, acid: 5.2, label: 'Small Ants', tag: 'Regular Ants' },
  Normal: { base: 5.0, worker: 5.0, fire: 5.4, acid: 5.4, label: 'Small Ants', tag: 'Regular Ants' },
  Hard: { base: 5.2, worker: 5.2, fire: 5.6, acid: 5.6, label: 'Fast Swarm', tag: 'Regular Ants' },
  Harder: { base: 5.4, worker: 5.4, fire: 5.8, acid: 5.8, label: 'Dense Swarm', tag: 'Regular Ants' },
  Insane: { base: 5.6, worker: 5.6, fire: 6.0, acid: 6.0, label: 'Colony Swarm', tag: 'Regular Ants' },
  Crazy: { base: 5.0, worker: 5.0, fire: 5.4, acid: 5.4, titan: 12.0, label: '2 Sentinels + Swarm', tag: 'Regular Ants Swarm' },
};

export const FREE_MODE_LEVEL: LevelConfig = {
  id: 999,
  name: 'Endless Free Mode',
  difficulty: 'Crazy',
  difficultyColor: '#60a5fa',
  songUrl: 'https://www.newgrounds.com/audio/listen/1418933',
  songTitle: 'Endless Randomizer',
  artist: 'Dynamic Shift Engine',
  bpm: 155,
  durationSeconds: 999999,
  themeColor: '#ffffff',
  bgColor: '#000000',
  spawnerCount: 5,
  maxAnts: 120,
  isEndless: true,
  mechanicId: 'dynamic_chaos',
  mechanicName: 'dynamic chaos',
  mechanicHint: 'clickable defenses & interactive pods shift continuously',
};